const KEY="fuyuko_demo_v4", SESSION_KEY=KEY+"_session";
const CATEGORIES=["From Marketplace","Server Utility","Redstone","Farming","PVP","Combat","Survival","Utility","World Generation","Mobs","Weapons","Armor","Tools","Magic","Economy","Minigame","UI","Shader","Texture","Optimization","Adventure","Building","Decoration","Transportation","Other"];
const DEFAULT_ADMIN={id:"u_admin",username:"HarsanAdmin1",password:"@harsan28.fuyuko.web.id",name:"Harsan Admin",avatar:"",role:"admin"};
let db=loadDB(),session=loadSession(),currentAddon=null,selectedRating=0;
const $=id=>document.getElementById(id), now=()=>Date.now();
const clone=x=>JSON.parse(JSON.stringify(x));
function normalizePath(p=""){p=String(p).trim().replace(/^\/+/,""); if(/^https?:\/\//i.test(p)||p.startsWith("data:")) return p; return p;}
function assetPath(p=""){p=normalizePath(p); return p || "";}
function escape(s=""){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));}
function save(){try{localStorage.setItem(KEY,JSON.stringify(db))}catch(e){toast("Data terlalu besar untuk penyimpanan browser.",true)}}
function loadSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||"null")}catch{return null}}
function saveSession(){if(session)localStorage.setItem(SESSION_KEY,JSON.stringify(session));else localStorage.removeItem(SESSION_KEY)}
function loadDB(){
  try{
    const raw=localStorage.getItem(KEY); if(raw){const x=JSON.parse(raw);if(x&&Array.isArray(x.users))return migrate(x)}
    for(const k of ["fuyuko_demo_v3","fuyuko_demo_v2"]){const raw=localStorage.getItem(k);if(raw){const x=JSON.parse(raw);if(x&&Array.isArray(x.users))return migrate(x)}}
  }catch(e){console.warn(e)}
  return {users:[clone(DEFAULT_ADMIN)],addons:[],requests:[]};
}
function migrate(x){
  x.users=Array.isArray(x.users)?x.users:[];
  let admin=x.users.find(u=>u.role==="admin")||x.users.find(u=>u.username==="admin");
  if(admin){admin.username=DEFAULT_ADMIN.username;admin.password=DEFAULT_ADMIN.password;admin.name=DEFAULT_ADMIN.name;admin.role="admin";admin.id="u_admin"}
  else x.users.unshift(clone(DEFAULT_ADMIN));
  x.users=x.users.filter((u,i,a)=>a.findIndex(v=>v.username.toLowerCase()===String(u.username).toLowerCase())===i);
  x.addons=Array.isArray(x.addons)?x.addons:[]; x.requests=Array.isArray(x.requests)?x.requests:[];
  x.addons=x.addons.filter(a=>!['fast-hopper','planting-block'].includes(a.id));
  x.addons.forEach(a=>{a.tags=Array.isArray(a.tags)?a.tags:(a.category?[a.category]:[]);a.releases=Array.isArray(a.releases)?a.releases:[];if(!a.releases.length)a.releases=[{id:"rel_"+a.id,version:a.release||"1.0.0",mcVersion:a.version||"",filePath:normalizePath(a.file||a.download||""),changelog:a.changelog||"",createdAt:a.updatedAt||a.createdAt||now()}];a.comments=Array.isArray(a.comments)?a.comments:[];a.ratings=a.ratings||{};a.features=Array.isArray(a.features)?a.features:[];a.updatedAt=Math.max(...a.releases.map(r=>r.createdAt||0),a.updatedAt||a.createdAt||0)});
  x.requests.forEach(r=>{r.visibility=r.visibility||"private";r.comments=Array.isArray(r.comments)?r.comments:[];r.supports=Array.isArray(r.supports)?r.supports:[];r.status=r.status||"pending"});
  return x;
}
function user(){return db.users.find(u=>u.id===session?.userId)}
function toast(msg,error=false){const t=$("toast");t.textContent=msg;t.className="toast show"+(error?" error":"");clearTimeout(toast.timer);toast.timer=setTimeout(()=>{t.textContent="";t.className="toast"},2200)}
function showPage(id){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));const p=$(id);if(!p)return;p.classList.add("active");$("nav").classList.remove("open");window.scrollTo(0,0);if(id==="home")renderFeatured();if(id==="addons")renderAddons();if(id==="profile")renderProfile();if(id==="admin")renderAdmin();if(id==="requests")renderRequestPage()}
document.addEventListener("click",e=>{const x=e.target.closest("[data-page]");if(x){e.preventDefault();showPage(x.dataset.page)}});
$("menuBtn").onclick=()=>$("nav").classList.toggle("open");$("loginBtn").onclick=()=>$("authModal").classList.remove("hidden");$("closeAuth").onclick=()=>$("authModal").classList.add("hidden");
document.querySelectorAll("[data-auth]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-auth]").forEach(x=>x.classList.toggle("active",x===b));$("loginForm").classList.toggle("hidden",b.dataset.auth!=="login");$("registerForm").classList.toggle("hidden",b.dataset.auth!=="register")});
function updateNav(){const u=user(),ok=!!u;document.querySelectorAll(".auth-only").forEach(x=>x.classList.toggle("hidden",!ok));document.querySelectorAll(".admin-only").forEach(x=>x.classList.toggle("hidden",u?.role!=="admin"));$("loginBtn").classList.toggle("hidden",ok);$("logoutBtn").classList.toggle("hidden",!ok)}
$("logoutBtn").onclick=()=>{session=null;saveSession();updateNav();showPage("home");toast("Berhasil logout")};
$("loginForm").onsubmit=e=>{e.preventDefault();const q=$("loginUser").value.trim().toLowerCase(),p=$("loginPass").value,u=db.users.find(x=>String(x.username).toLowerCase()===q);if(!u||u.password!==p)return toast("Login gagal. Periksa username dan password.",true);session={userId:u.id};saveSession();updateNav();$("authModal").classList.add("hidden");e.target.reset();toast("Login berhasil");showPage(u.role==="admin"?"admin":"home")};
$("registerForm").onsubmit=e=>{e.preventDefault();const username=$("regUser").value.trim(),password=$("regPass").value;if(!/^[a-zA-Z0-9_.-]{3,24}$/.test(username))return toast("Username hanya boleh huruf, angka, _, ., -",true);if(db.users.some(u=>u.username.toLowerCase()===username.toLowerCase()))return toast("Username sudah dipakai.",true);const u={id:"u_"+now()+Math.random().toString(36).slice(2,6),username,password,name:$("regName").value.trim()||username,avatar:"",role:"user"};db.users.push(u);save();session={userId:u.id};saveSession();updateNav();$("authModal").classList.add("hidden");e.target.reset();toast("Akun berhasil dibuat");showPage("home")};
function releases(a){return (a.releases||[]).slice().sort((x,y)=>(y.createdAt||0)-(x.createdAt||0))} function latestRelease(a){return releases(a)[0]||null}
function avg(a){const v=Object.values(a.ratings||{}).map(Number).filter(x=>x>0);return v.length?Math.round(v.reduce((s,n)=>s+n,0)/v.length*2)/2:0}
function starHTML(n){return `<span class="five-stars" aria-label="${n}/5">${[0,1,2,3,4].map(i=>{const f=Math.max(0,Math.min(1,n-i));return `<span class="star-unit" style="--fill:${f*100}%">★</span>`}).join("")}</span>`}
function ratingPickerHTML(n){return `<div class="rating-picker">${[0,1,2,3,4].map(i=>{const f=Math.max(0,Math.min(1,n-i));return `<span class="pick-star" style="--fill:${f*100}%"><span class="pick-base">★</span><span class="pick-fill">★</span><button class="pick-half left" onclick="setRating(${i+.5})" aria-label="${i+.5}/5"></button><button class="pick-half right" onclick="setRating(${i+1})" aria-label="${i+1}/5"></button></span>`}).join("")}</div>`}
function sortedAddons(){return [...db.addons].sort((a,b)=>(b.updatedAt||b.createdAt||0)-(a.updatedAt||a.createdAt||0))}
function card(a){const r=latestRelease(a),isNew=a.updatedAt&&now()-a.updatedAt<14*86400000;const src=assetPath(a.image);const img=src?`<img src="${escape(src)}" alt="${escape(a.name)}" onerror="this.closest('.thumb').classList.add('img-error');this.remove()">`:`<div class="thumb placeholder">FW</div>`;return `<article class="card"><div class="thumb">${img}<span class="image-fallback">FW</span>${isNew?'<span class="update-badge">UPDATE BARU</span>':""}</div><div class="card-body"><div class="tags">${(a.tags||[]).slice(0,3).map(t=>`<span class="tag">${escape(t)}</span>`).join("")}</div><h3>${escape(a.name)}</h3><p class="muted">${escape((a.description||"").slice(0,105))}${(a.description||"").length>105?"…":""}</p><div class="rating">${starHTML(avg(a))}<span class="muted">${avg(a).toFixed(1)} (${Object.keys(a.ratings||{}).length})</span></div><div class="tags"><span class="tag">MC ${escape(r?.mcVersion||"-")}</span><span class="tag">v${escape(r?.version||"-")}</span></div><div class="card-footer"><span class="muted">${a.downloads||0} downloads</span><button class="btn small" onclick="openAddon('${a.id}')">Details</button></div></div></article>`}
function renderFeatured(){$("featuredGrid").innerHTML=sortedAddons().slice(0,4).map(card).join("")||"<p class='muted'>Belum ada addon.</p>"}
function renderFilters(){const cats=[...new Set(db.addons.flatMap(a=>a.tags||[]))].sort(),vers=[...new Set(db.addons.flatMap(a=>(a.releases||[]).map(r=>r.mcVersion).filter(Boolean)))].sort();$("categoryFilter").innerHTML='<option value="">All categories</option>'+cats.map(x=>`<option>${escape(x)}</option>`).join("");$("versionFilter").innerHTML='<option value="">All versions</option>'+vers.map(x=>`<option>${escape(x)}</option>`).join("")}
function renderAddons(){renderFilters();const q=$("searchInput").value.trim().toLowerCase(),c=$("categoryFilter").value,v=$("versionFilter").value;const arr=sortedAddons().filter(a=>(!q||(a.name+" "+a.description+" "+(a.tags||[]).join(" ")+" "+(a.releases||[]).map(r=>r.version+" "+r.mcVersion).join(" ")).toLowerCase().includes(q))&&(!c||(a.tags||[]).includes(c))&&(!v||(a.releases||[]).some(r=>r.mcVersion===v)));$("addonGrid").innerHTML=arr.map(card).join("")||"<p class='muted'>Addon tidak ditemukan.</p>"}
["searchInput","categoryFilter","versionFilter"].forEach(id=>$(id).addEventListener("input",renderAddons));
function commentTree(comments){const roots=comments.filter(c=>!c.parentId);const children=id=>comments.filter(c=>c.parentId===id);const draw=c=>`<div class="comment"><div class="comment-head"><b>${escape(c.user)}</b><span class="muted">${new Date(c.date).toLocaleString()}</span></div><p>${escape(c.text)}</p>${user()?`<button class="text-btn reply-btn" onclick="replyComment('${c.id}')">Balas</button>`:""}${children(c.id).map(draw).join("")}</div>`;return roots.map(draw).join("")}
window.replyComment=id=>{const el=$("commentText");el.focus();el.dataset.parent=id;el.placeholder="Membalas komentar…";toast("Mode balas aktif. Tulis komentar lalu kirim.")};
function renderComments(a){const box=$("commentsList"),count=(a.comments||[]).length;box.innerHTML=count?commentTree(a.comments):'<p class="muted">Belum ada komentar.</p>';$("commentCount").textContent=count}
window.openAddon=id=>{const a=db.addons.find(x=>x.id===id);if(!a)return;currentAddon=id;selectedRating=Number(a.ratings?.[user()?.id]||0);showPage("detail");const rs=releases(a),src=assetPath(a.image);$("detailContent").innerHTML=`<div class="detail-wrap"><div class="detail-cover">${src?`<img src="${escape(src)}" alt="${escape(a.name)}" onerror="this.remove();this.parentElement.classList.add('img-error')">`:`<div class='thumb placeholder'>FW</div>`}<span class="image-fallback">FW</span></div><div class="detail-body"><div class="tags">${(a.tags||[]).map(t=>`<span class="tag">${escape(t)}</span>`).join("")}</div><h1>${escape(a.name)}</h1><p class="muted">by ${escape(a.author||"Unknown")} · ${a.downloads||0} downloads</p><div class="rating">${starHTML(avg(a))}<b>${avg(a).toFixed(1)}/5</b><span class="muted">${Object.keys(a.ratings||{}).length} rating</span></div><p>${escape(a.description||"")}</p><div class="tags">${(a.features||[]).map(f=>`<span class="tag">${escape(f)}</span>`).join("")}</div><h2>Versions & Files</h2><div class="release-list">${rs.map((r,i)=>`<div class="release-row"><div><b>v${escape(r.version)}</b> <span class="tag">MC ${escape(r.mcVersion||"-")}</span>${i===0?'<span class="update-badge inline">LATEST</span>':""}<p class="muted">${escape(r.changelog||"No changelog")}</p><small class="muted">${escape(r.filePath||"")}</small></div><button class="btn small" onclick="downloadRelease('${a.id}','${r.id}')">Download</button></div>`).join("")}</div>${user()?`<div class="rating-box"><span class="muted">Pilih rating 0,5–5</span>${ratingPickerHTML(selectedRating)}<span class="muted">Rating kamu: ${selectedRating||"belum ada"}</span></div><div class="comment-form"><textarea id="commentText" class="input" rows="3" placeholder="Tulis komentar…"></textarea><button class="btn small" onclick="postComment()">Kirim komentar</button></div>`:`<div class="panel"><p class="muted">Login untuk memberi rating dan komentar.</p></div>`}<section class="comments-section"><div class="comments-title"><h2>Komentar (<span id="commentCount">0</span>)</h2><span class="muted">Komentar dibalas di bawah komentar asal.</span></div><div id="commentsList" class="comments-list"></div></section></div></div>`;renderComments(a)};
window.setRating=v=>{const u=user();if(!u)return toast("Login untuk memberi rating.",true);const a=db.addons.find(x=>x.id===currentAddon);a.ratings=a.ratings||{};a.ratings[u.id]=v;selectedRating=v;save();openAddon(a.id);toast("Rating disimpan")};
window.postComment=()=>{const u=user(),a=db.addons.find(x=>x.id===currentAddon),text=$("commentText")?.value.trim();if(!u||!a||!text)return;if(text.length>1000)return toast("Komentar terlalu panjang.",true);a.comments=a.comments||[];a.comments.push({id:"c_"+now()+Math.random().toString(36).slice(2,5),user:u.name||u.username,userId:u.id,text,parentId:$("commentText").dataset.parent||null,date:now()});save();openAddon(a.id);toast("Komentar ditambahkan")};
window.downloadRelease=(aid,rid)=>{const a=db.addons.find(x=>x.id===aid),r=a?.releases.find(x=>x.id===rid);if(!a||!r)return;const path=assetPath(r.filePath);if(!path)return toast("File download belum diatur admin.",true);a.downloads=(a.downloads||0)+1;save();const link=document.createElement("a");link.href=path;link.download="";link.target="_blank";document.body.appendChild(link);link.click();link.remove()};
function renderProfile(){const u=user();if(!u){showPage("home");return}$("profileUsername").value=u.username;$("profileName").value=u.name||"";$("profileAvatar").value=u.avatar||"";$("profileHeading").textContent=u.name||u.username;$("profileAvatarPreview").innerHTML=u.avatar?`<img src="${escape(assetPath(u.avatar))}">`:escape((u.name||u.username)[0].toUpperCase())}
$("profileForm").onsubmit=e=>{e.preventDefault();const u=user();u.name=$("profileName").value.trim()||u.username;u.avatar=normalizePath($("profileAvatar").value);save();renderProfile();toast("Profile disimpan")};$("passwordForm").onsubmit=e=>{e.preventDefault();const u=user();if($("oldPassword").value!==u.password)return toast("Password lama salah.",true);u.password=$("newPassword").value;save();e.target.reset();toast("Password berhasil diubah")};
function requireAdmin(){if(user()?.role!=="admin"){toast("Akses admin ditolak.",true);showPage("home");return false}return true}
function renderCategoryChoices(selected=[]){const box=$("categoryChoices");box.innerHTML=CATEGORIES.map(c=>`<label class="check-item"><input type="checkbox" value="${escape(c)}" ${selected.includes(c)?"checked":""}> <span>${escape(c)}</span></label>`).join("");const update=()=>$("categorySummary").textContent=(selectedCategories().length?`${selectedCategories().length} kategori dipilih`:"Pilih kategori");box.querySelectorAll("input").forEach(i=>i.onchange=update);update()}
function selectedCategories(){return [...document.querySelectorAll("#categoryChoices input:checked")].map(x=>x.value)}
function clearAddonForm(){$("addonForm").reset();$("editAddonId").value="";$("addonFormTitle").textContent="Tambah Addon";$("releaseSection").classList.add("hidden");$("addonInfoSection").classList.remove("hidden");$("addonForm").classList.add("hidden");renderCategoryChoices([])}
function renderAdmin(){if(!requireAdmin())return;$("stats").innerHTML=`<div class="stat"><span class="muted">Addons</span><b>${db.addons.length}</b></div><div class="stat"><span class="muted">Users</span><b>${db.users.length}</b></div><div class="stat"><span class="muted">Requests</span><b>${db.requests.length}</b></div><div class="stat"><span class="muted">Downloads</span><b>${db.addons.reduce((n,a)=>n+(a.downloads||0),0)}</b></div>`;renderAdminAddons();renderAdminRequests();renderAdminUsers();clearAddonForm()}
function renderAdminAddons(){$("adminAddonList").innerHTML=sortedAddons().map(a=>{const r=latestRelease(a);return `<div class="admin-addon"><div class="admin-addon-main"><div><h3>${escape(a.name)}</h3><div class="tags">${(a.tags||[]).map(t=>`<span class="tag">${escape(t)}</span>`).join("")}</div><p class="muted">Terbaru v${escape(r?.version||"-")} · MC ${escape(r?.mcVersion||"-")} · ${a.releases.length} file/version</p></div><div class="actions"><button class="btn small ghost" onclick="editAddon('${a.id}')">Kelola / Update</button><button class="btn small danger" onclick="deleteAddon('${a.id}')">Hapus</button></div></div><div class="release-admin-list">${releases(a).map(rel=>`<div class="release-admin"><div><b>v${escape(rel.version)}</b> <span class="tag">MC ${escape(rel.mcVersion||"-")}</span>${rel===r?'<span class="update-badge inline">TERBARU</span>':""}<p class="muted">${escape(rel.changelog||"Tidak ada changelog")}</p><code>${escape(rel.filePath||"-" )}</code></div><button class="btn small danger ghost" onclick="deleteRelease('${a.id}','${rel.id}')">Hapus file</button></div>`).join("")}</div></div>`}).join("")||"<p class='muted admin-empty'>Belum ada addon.</p>"}
$("showAddonForm").onclick=()=>{$("addonForm").classList.remove("hidden");$("addonInfoSection").classList.remove("hidden");$("releaseSection").classList.add("hidden");$("editAddonId").value="";$('addonFormTitle').textContent="Tambah Addon Baru";renderCategoryChoices([]);window.scrollTo({top:250,behavior:"smooth"})};$("cancelEdit").onclick=clearAddonForm;
$("addonForm").onsubmit=e=>{e.preventDefault();if(!requireAdmin())return;const name=$("addonName").value.trim(),tags=selectedCategories(),mc=$("addonVersion").value.trim(),release=$("addonRelease").value.trim()||"1.0.0",file=$("addonFilePath").value.trim(),image=normalizePath($("addonImage").value),id=$("editAddonId").value;if(!name||!mc||!file||!image||!tags.length)return toast("Nama, MC version, path file, thumbnail, dan minimal satu tag wajib.",true);const stamp=now();if(id){const a=db.addons.find(x=>x.id===id);a.name=name;a.tags=tags;a.image=image;a.video=$("addonVideo").value.trim();a.author=$("addonAuthor").value.trim()||"Fuyuko Team";a.description=$("addonDescription").value.trim();a.features=$("addonFeatures").value.split(",").map(x=>x.trim()).filter(Boolean);const newFile=normalizePath(file);if(newFile){a.releases.push({id:"rel_"+stamp+Math.random().toString(36).slice(2,5),version:release,mcVersion:mc,filePath:newFile,changelog:$("addonChangelog").value.trim(),createdAt:stamp})}a.updatedAt=stamp}else db.addons.push({id:"a_"+stamp+Math.random().toString(36).slice(2,6),name,tags,image,video:$("addonVideo").value.trim(),author:$("addonAuthor").value.trim()||"Fuyuko Team",description:$("addonDescription").value.trim(),features:$("addonFeatures").value.split(",").map(x=>x.trim()).filter(Boolean),downloads:0,comments:[],ratings:{},createdAt:stamp,updatedAt:stamp,releases:[{id:"rel_"+stamp,version:release,mcVersion:mc,filePath:normalizePath(file),changelog:$("addonChangelog").value.trim(),createdAt:stamp}]});save();clearAddonForm();renderAdmin();renderFeatured();renderAddons();toast(id?"File versi baru ditambahkan.":"Addon berhasil dibuat.")};
window.editAddon=id=>{const a=db.addons.find(x=>x.id===id);if(!a)return;$("editAddonId").value=id;$("addonFormTitle").textContent="Edit Info Addon";$("addonName").value=a.name;$("addonImage").value=a.image||"";$("addonVideo").value=a.video||"";$("addonAuthor").value=a.author||"";$("addonDescription").value=a.description||"";$("addonFeatures").value=(a.features||[]).join(", ");$("addonVersion").value=latestRelease(a)?.mcVersion||"";$("addonRelease").value="";$("addonFilePath").value="";$("addonChangelog").value="";renderCategoryChoices(a.tags||[]);$("addonForm").classList.remove("hidden");$("addonInfoSection").classList.remove("hidden");$("releaseSection").removeAttribute("hidden");renderVersionManager(a);window.scrollTo({top:250,behavior:"smooth"})};
function renderVersionManager(a){$("versionManager").innerHTML=releases(a).map(r=>`<div class="release-admin"><div><b>v${escape(r.version)}</b> <span class="tag">MC ${escape(r.mcVersion||"-")}</span><p class="muted">${escape(r.changelog||"Tidak ada changelog")}</p><code>${escape(r.filePath||"-")}</code></div><button class="btn small danger" onclick="deleteRelease('${a.id}','${r.id}')">Hapus file</button></div>`).join("")}
$("addVersionBtn").onclick=()=>{const id=$("editAddonId").value;if(!id)return;$("releaseSection").classList.remove("hidden");$("addonRelease").focus()};
window.deleteRelease=(aid,rid)=>{if(!requireAdmin())return;const a=db.addons.find(x=>x.id===aid);if(!a||a.releases.length<=1)return toast("Addon harus menyimpan minimal satu file versi.",true);if(!confirm("Hapus file versi ini dari daftar?"))return;a.releases=a.releases.filter(r=>r.id!==rid);a.updatedAt=now();save();renderAdmin();renderFeatured();toast("File versi dihapus dari daftar")};window.deleteAddon=id=>{if(!requireAdmin()||!confirm("Hapus addon beserta semua versinya?"))return;db.addons=db.addons.filter(a=>a.id!==id);save();renderAdmin();renderFeatured();toast("Addon dihapus")};
function requestVisible(r){return r.visibility==="public"||r.userId===user()?.id||user()?.role==="admin"}
function requestCard(r,admin=false){const supported=r.supports?.length||0,yes=r.supports?.includes(user()?.id);return `<article class="request-card"><div class="request-head"><div><h3>${escape(r.title)}</h3><p class="muted">oleh ${escape(r.user)} · ${new Date(r.date).toLocaleString()} · ${r.visibility}</p></div><span class="tag">${escape(r.status)}</span></div><p>${escape(r.text)}</p>${r.file?`<button class="text-btn" onclick="downloadRequestFile('${r.id}')">Download file referensi: ${escape(r.file.name)}</button>`:""}<div class="request-actions"><button class="btn small ${yes?"":"ghost"}" onclick="toggleSupport('${r.id}')">☑ ${yes?"Kamu setuju":"Centang untuk setujui requestan ini"}</button><b>${supported} User setuju dengan request ini</b></div><div class="request-comments">${(r.comments||[]).map(c=>`<div class="request-comment"><b>${escape(c.user)}</b><span class="muted">${new Date(c.date).toLocaleString()}</span><p>${escape(c.text)}</p></div>`).join("")}</div>${user()?`<div class="request-reply"><input class="input" id="reqc_${r.id}" placeholder="Balas request ini..."><button class="btn small" onclick="commentRequest('${r.id}')">Balas</button></div>`:""}${admin?`<div class="request-admin-actions"><button class="btn small" onclick="setRequest('${r.id}','accepted')">Setujui</button><button class="btn small ghost" onclick="setRequest('${r.id}','rejected')">Tolak</button><button class="btn small danger" onclick="deleteRequest('${r.id}')">Hapus</button></div>`:""}</article>`}
function renderRequestPage(){const u=user();$("requestGate").innerHTML=u?"":'<div class="panel"><h3>Login diperlukan</h3><p class="muted">Login untuk mengirim request, memberi dukungan, atau membalas.</p><button class="btn" id="requestLogin">Login / Register</button></div>';$("requestForm").classList.toggle("hidden",!u);const publicReq=db.requests.filter(r=>r.visibility==="public").sort((a,b)=>b.date-a.date);$("publicRequests").innerHTML=publicReq.length?publicReq.map(r=>requestCard(r)).join(""):"<p class='muted'>Belum ada request public.</p>";const b=$("requestLogin");if(b)b.onclick=()=>$("authModal").classList.remove("hidden")}
$("requestForm").onsubmit=async e=>{e.preventDefault();const u=user();if(!u)return;const file=$("reqFile").files[0];let fd=null;if(file){if(file.size>2*1024*1024)return toast("File maksimal 2 MB.",true);fd={name:file.name,type:file.type,size:file.size,data:await readFile(file)}}db.requests.push({id:"r_"+now(),userId:u.id,user:u.name||u.username,title:$("reqTitle").value.trim(),text:$("reqText").value.trim(),file:fd,visibility:$("reqPublic").checked?"public":"private",status:"pending",supports:[],comments:[],date:now()});save();e.target.reset();renderRequestPage();toast("Request tersimpan")};
function readFile(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
window.toggleSupport=id=>{const u=user();if(!u)return toast("Login diperlukan.",true);const r=db.requests.find(x=>x.id===id);if(!r)return;if(r.userId===u.id)return toast("Kamu tidak perlu mendukung request sendiri.",true);r.supports=r.supports||[];r.supports.includes(u.id)?r.supports=r.supports.filter(x=>x!==u.id):r.supports.push(u.id);save();renderRequestPage();renderAdminRequests()};window.commentRequest=id=>{const u=user(),r=db.requests.find(x=>x.id===id),el=$("reqc_"+id);if(!u||!r||!el?.value.trim())return;r.comments=r.comments||[];r.comments.push({id:"rc_"+now(),user:u.name||u.username,text:el.value.trim(),date:now()});save();renderRequestPage();renderAdminRequests()};
window.downloadRequestFile=id=>{const r=db.requests.find(x=>x.id===id);if(!r?.file?.data)return;const a=document.createElement("a");a.href=r.file.data;a.download=r.file.name;document.body.appendChild(a);a.click();a.remove()};
function renderAdminRequests(){const arr=db.requests.slice().sort((a,b)=>b.date-a.date);$("adminRequestList").innerHTML=arr.length?arr.map(r=>requestCard(r,true)).join(""):"<p class='muted'>Belum ada request.</p>"}
window.setRequest=(id,status)=>{const r=db.requests.find(x=>x.id===id);if(!r)return;r.status=status;save();renderAdminRequests();renderRequestPage();toast("Status request diperbarui")};window.deleteRequest=id=>{if(!requireAdmin())return;if(!confirm("Hapus request ini?"))return;db.requests=db.requests.filter(x=>x.id!==id);save();renderAdminRequests();renderRequestPage();toast("Request dihapus")};
function renderAdminUsers(){$("adminUserList").innerHTML=db.users.map(u=>`<div class="admin-item"><div class="user-line"><div class="avatar">${u.avatar?`<img src="${escape(assetPath(u.avatar))}">`:escape((u.name||u.username)[0].toUpperCase())}</div><div><b>${escape(u.name||u.username)}</b><div class="muted">@${escape(u.username)} · ${escape(u.role)}</div></div></div><div class="actions">${u.id!==user()?.id?`<button class="btn small ghost" onclick="toggleAdmin('${u.id}')">${u.role==="admin"?"Jadikan User":"Jadikan Admin"}</button>`:""}</div></div>`).join("")}
window.toggleAdmin=id=>{if(!requireAdmin())return;const u=db.users.find(x=>x.id===id);if(!u)return;u.role=u.role==="admin"?"user":"admin";save();renderAdminUsers();updateNav();toast("Role diperbarui")};
document.querySelectorAll(".admin-tabs .tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".admin-tabs .tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".admin-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.tab).classList.add("active")});
$("requestSearch").addEventListener("input",()=>{const q=$("requestSearch").value.toLowerCase();document.querySelectorAll("#publicRequests .request-card").forEach(c=>c.classList.toggle("hidden",!c.innerText.toLowerCase().includes(q)))});
renderCategoryChoices([]);updateNav();renderFeatured();renderRequestPage();
