const KEY="fuyuko_demo_v3", SESSION_KEY=KEY+"_session";

const CATEGORIES=["From Marketplace","Server Utility","Redstone","Farming","PVP","Combat","Survival","Utility","World Generation","Mobs","Weapons","Armor","Tools","Magic","Economy","Minigame","UI","Shader","Texture","Optimization","Adventure","Building","Decoration","Transportation","Other"];
const oldKeys=["fuyuko_demo_v2"];
const defaultData={users:[{id:"u_admin",username:"admin",password:"Admin123!",name:"Fuyuko Admin",avatar:"",role:"admin"}],addons:[],requests:[]};
let db=loadDB(),session=loadSession(),currentAddon=null,selectedRating=0;
const $=id=>document.getElementById(id);
const now=()=>Date.now();
function clone(x){return JSON.parse(JSON.stringify(x));}
function loadDB(){
  try{
    const raw=localStorage.getItem(KEY);
    if(raw){const x=JSON.parse(raw); if(x&&Array.isArray(x.users)&&Array.isArray(x.addons)) return migrate(x);}
    for(const k of oldKeys){const rawOld=localStorage.getItem(k);if(rawOld){const x=JSON.parse(rawOld);if(x&&Array.isArray(x.users)){return migrate(x);}}}
  }catch(e){console.warn("Fuyuko DB load error",e)}
  return clone(defaultData);
}
function migrate(x){
  x.requests=Array.isArray(x.requests)?x.requests:[];
  x.users=x.users.length?x.users:clone(defaultData.users);
  // Remove the two old demo addons requested by the site owner.
  x.addons=(x.addons||[]).filter(a=>!['fast-hopper','planting-block'].includes(a.id));
  x.addons.forEach(a=>{
    a.tags=Array.isArray(a.tags)?a.tags:(a.category?[a.category]:[]);
    a.releases=Array.isArray(a.releases)&&a.releases.length?a.releases:[{id:"rel_"+a.id,version:a.release||"1.0.0",mcVersion:a.version||"",file:a.file||null,externalUrl:a.download||"",changelog:a.changelog||"",createdAt:a.updatedAt||a.createdAt||now()}];
    a.downloads=a.downloads||0;a.comments=a.comments||[];a.ratings=a.ratings||{};a.createdAt=a.createdAt||now();a.updatedAt=Math.max(...a.releases.map(r=>r.createdAt||0),a.updatedAt||a.createdAt);
  });
  return x;
}
function save(){try{localStorage.setItem(KEY,JSON.stringify(db));}catch(e){toast("Penyimpanan browser penuh. File addon mungkin terlalu besar.",true);console.error(e)}}
function loadSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||"null")}catch{return null}}
function saveSession(){if(session)localStorage.setItem(SESSION_KEY,JSON.stringify(session));else localStorage.removeItem(SESSION_KEY)}
function user(){return db.users.find(u=>u.id===session?.userId)}
function escape(s=""){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]))}
function toast(msg,error=false){const t=$("toast");t.textContent=msg;t.className="toast"+(error?" error":"");clearTimeout(toast.timer);toast.timer=setTimeout(()=>{t.textContent="";t.className=""},2600)}
function showPage(id){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));const p=$(id);if(!p)return;p.classList.add("active");$("nav").classList.remove("open");window.scrollTo(0,0);if(id==="home")renderFeatured();if(id==="addons")renderAddons();if(id==="profile")renderProfile();if(id==="admin")renderAdmin();if(id==="requests")renderRequestPage()}
document.addEventListener("click",e=>{const x=e.target.closest("[data-page]");if(x){e.preventDefault();showPage(x.dataset.page)}});
$("menuBtn").addEventListener("click",()=>$("nav").classList.toggle("open"));
$("loginBtn").addEventListener("click",()=>$("authModal").classList.remove("hidden"));
$("closeAuth").addEventListener("click",()=>$("authModal").classList.add("hidden"));
document.querySelectorAll("[data-auth]").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll("[data-auth]").forEach(x=>x.classList.toggle("active",x===b));$("loginForm").classList.toggle("hidden",b.dataset.auth!=="login");$("registerForm").classList.toggle("hidden",b.dataset.auth!=="register")}));
function updateNav(){const u=user(),logged=!!u;document.querySelectorAll(".auth-only").forEach(x=>x.classList.toggle("hidden",!logged));document.querySelectorAll(".admin-only").forEach(x=>x.classList.toggle("hidden",u?.role!=="admin"));$("loginBtn").classList.toggle("hidden",logged);$("logoutBtn").classList.toggle("hidden",!logged)}
$("logoutBtn").addEventListener("click",()=>{session=null;saveSession();updateNav();showPage("home");toast("Berhasil logout")});
$("loginForm").addEventListener("submit",e=>{e.preventDefault();const q=$("loginUser").value.trim().toLowerCase(),p=$("loginPass").value;const u=db.users.find(x=>String(x.username||"").toLowerCase()===q);if(!u||u.password!==p){toast("Login gagal. Periksa username dan password.",true);return}session={userId:u.id};saveSession();updateNav();$("authModal").classList.add("hidden");e.target.reset();toast("Login berhasil");showPage(u.role==="admin"?"admin":"home")});
$("registerForm").addEventListener("submit",e=>{e.preventDefault();const username=$("regUser").value.trim(),password=$("regPass").value;if(!/^[a-zA-Z0-9_.-]{3,24}$/.test(username))return toast("Username hanya boleh huruf, angka, _, ., -",true);if(db.users.some(u=>String(u.username).toLowerCase()===username.toLowerCase()))return toast("Username sudah dipakai.",true);const u={id:"u_"+now()+"_"+Math.random().toString(36).slice(2,7),username,password,name:$("regName").value.trim()||username,avatar:"",role:"user"};db.users.push(u);save();session={userId:u.id};saveSession();updateNav();$("authModal").classList.add("hidden");e.target.reset();toast("Akun berhasil dibuat");showPage("home")});
function releases(a){return (a.releases||[]).slice().sort((x,y)=>(y.createdAt||0)-(x.createdAt||0))}
function latestRelease(a){return releases(a)[0]||null}
function avg(a){const vals=Object.values(a.ratings||{}).map(Number).filter(x=>x>0);return vals.length?Math.round(vals.reduce((x,y)=>x+y,0)/vals.length*2)/2:0}
function stars(n){return Array.from({length:5},(_,i)=>i+1<=Math.floor(n)?"★":(i+0.5===n?"⯨":"☆")).join("")}
function sortedAddons(){return [...db.addons].sort((a,b)=>(b.updatedAt||b.createdAt||0)-(a.updatedAt||a.createdAt||0))}
function card(a){const r=latestRelease(a),isNew=a.updatedAt&&now()-a.updatedAt<14*86400000;const img=a.image?`<img src="${escape(a.image)}" alt="${escape(a.name)}" onerror="this.style.display='none'">`:`<div class="thumb placeholder">FW</div>`;const tags=(a.tags||[]).slice(0,3);return `<article class="card"><div class="thumb">${img}${isNew?'<span class="update-badge">UPDATE BARU</span>':""}</div><div class="card-body"><div class="tags">${tags.map(t=>`<span class="tag">${escape(t)}</span>`).join("")}</div><h3>${escape(a.name)}</h3><p class="muted">${escape((a.description||"").slice(0,105))}${(a.description||"").length>105?"…":""}</p><div class="rating"><span class="stars">${stars(avg(a))}</span><span class="muted">${avg(a).toFixed(1)} (${Object.keys(a.ratings||{}).length})</span></div><div class="tags"><span class="tag">MC ${escape(r?.mcVersion||"-")}</span><span class="tag">v${escape(r?.version||"-")}</span></div><div class="card-footer"><span class="muted">${a.downloads||0} downloads</span><button class="btn small" onclick="openAddon('${a.id}')">Details</button></div></div></article>`}
function renderFeatured(){$("featuredGrid").innerHTML=sortedAddons().slice(0,4).map(card).join("")||"<p class='muted'>Belum ada addon.</p>"}
function renderFilters(){const cats=[...new Set(db.addons.flatMap(a=>a.tags||[]))].sort();const vers=[...new Set(db.addons.flatMap(a=>(a.releases||[]).map(r=>r.mcVersion).filter(Boolean)))].sort();$("categoryFilter").innerHTML='<option value="">All categories</option>'+cats.map(x=>`<option value="${escape(x)}">${escape(x)}</option>`).join("");$("versionFilter").innerHTML='<option value="">All versions</option>'+vers.map(x=>`<option value="${escape(x)}">${escape(x)}</option>`).join("")}
function renderAddons(){renderFilters();const q=$("searchInput").value.trim().toLowerCase(),c=$("categoryFilter").value,v=$("versionFilter").value;const arr=sortedAddons().filter(a=>(!q||(a.name+" "+a.description+" "+(a.tags||[]).join(" ")+" "+(a.releases||[]).map(r=>r.version+" "+r.mcVersion).join(" ")).toLowerCase().includes(q))&&(!c||(a.tags||[]).includes(c))&&(!v||(a.releases||[]).some(r=>r.mcVersion===v)));$("addonGrid").innerHTML=arr.map(card).join("")||"<p class='muted'>Addon tidak ditemukan.</p>"}
["searchInput","categoryFilter","versionFilter"].forEach(id=>$(id).addEventListener("input",renderAddons));
window.openAddon=id=>{const a=db.addons.find(x=>x.id===id);if(!a)return;currentAddon=id;selectedRating=Number(a.ratings?.[user()?.id]||0);showPage("detail");const rs=releases(a),comments=a.comments||[];$("detailContent").innerHTML=`<div class="detail-wrap"><div class="detail-cover">${a.image?`<img src="${escape(a.image)}" alt="">`:"<div class='thumb placeholder'>FW</div>"}</div><div class="detail-body"><div class="tags">${(a.tags||[]).map(t=>`<span class="tag">${escape(t)}</span>`).join("")}</div><h1>${escape(a.name)}</h1><p class="muted">by ${escape(a.author||"Unknown")} · ${a.downloads||0} downloads</p><div class="rating"><span class="stars">${stars(avg(a))}</span><b>${avg(a).toFixed(1)}/5</b><span class="muted">${Object.keys(a.ratings||{}).length} rating</span></div><p>${escape(a.description||"")}</p><div class="tags">${(a.features||[]).map(f=>`<span class="tag">${escape(f)}</span>`).join("")}</div><h2>Versions</h2><div class="release-list">${rs.map((r,i)=>`<div class="release-row"><div><b>v${escape(r.version)}</b> <span class="tag">MC ${escape(r.mcVersion||"-")}</span>${i===0?'<span class="update-badge inline">LATEST</span>':""}<p class="muted">${escape(r.changelog||"No changelog")}</p></div><button class="btn small" onclick="downloadRelease('${a.id}','${r.id}')">Download</button></div>`).join("")}</div>${user()?`<div class="rating-box"><span class="muted">Pilih rating 0,5–5</span><div class="star-input">${Array.from({length:10},(_,i)=>{const v=(i+1)/2;return `<button type="button" title="${v}/5" class="${selectedRating>=v?"active":""}" onclick="setRating(${v})">★</button>`}).join("")}</div><button class="btn small" onclick="saveRating()">Simpan rating</button></div>`:"<p class='muted'>Login untuk memberi rating.</p>"}<h2>Comments</h2><div id="comments">${comments.length?comments.map(c=>`<div class="comment"><strong>${escape(c.name)}</strong><span class="muted">${new Date(c.date).toLocaleString()}</span><p>${escape(c.text)}</p></div>`).join(""):"<p class='muted'>Belum ada komentar.</p>"}</div>${user()?`<form class="comment-form" id="commentForm"><textarea id="commentText" class="input" required rows="4" maxlength="1000" placeholder="Tulis komentar..."></textarea><button class="btn" type="submit">Post Comment</button></form>`:"<p class='muted'>Login untuk menulis komentar.</p>"}</div></div>`;const form=$("commentForm");if(form)form.addEventListener("submit",addComment)};
window.setRating=n=>{selectedRating=n;document.querySelectorAll(".star-input button").forEach((b,i)=>b.classList.toggle("active",selectedRating>=(i+1)/2));toast("Rating dipilih: "+selectedRating.toFixed(1)+"/5")};
window.saveRating=()=>{const u=user(),a=db.addons.find(x=>x.id===currentAddon);if(!u||!a||!selectedRating)return; a.ratings=a.ratings||{};a.ratings[u.id]=selectedRating;save();openAddon(a.id);toast("Rating disimpan")};
window.downloadRelease=(addonId,releaseId)=>{const a=db.addons.find(x=>x.id===addonId),r=a?.releases?.find(x=>x.id===releaseId);if(!a||!r)return;const target=r.filePath||r.file?.path||r.externalUrl;if(!target)return toast("File versi ini belum tersedia.",true);a.downloads=(a.downloads||0)+1;save();const link=document.createElement("a");link.href=target;link.download=(r.filePath||"").split("/").pop()||`${a.name}-v${r.version}`;link.target="_blank";link.rel="noopener";document.body.appendChild(link);link.click();link.remove();toast("Download dimulai")};
function addComment(e){e.preventDefault();const u=user(),a=db.addons.find(x=>x.id===currentAddon),text=$("commentText").value.trim();if(!u||!a||!text)return;a.comments.push({id:"c_"+now(),userId:u.id,name:u.name||u.username,text,date:now()});save();openAddon(a.id);toast("Komentar ditambahkan")}
function renderRequestPage(){if(!user()){$("requestGate").innerHTML='<div class="panel"><h3>Login diperlukan</h3><p class="muted">Login untuk mengirim request addon.</p><button class="btn" id="requestLogin">Login / Register</button></div>';$('requestForm').classList.add("hidden");const b=$("requestLogin");if(b)b.onclick=()=>$("authModal").classList.remove("hidden")}else{$("requestGate").innerHTML="";$('requestForm').classList.remove("hidden")}}
$("requestForm").addEventListener("submit",async e=>{e.preventDefault();const u=user();if(!u)return;const file=$("reqFile").files[0];let fileData=null;if(file){if(file.size>2*1024*1024)return toast("File request maksimal 2 MB.",true);fileData={name:file.name,type:file.type,size:file.size,data:await readFile(file)}}db.requests.push({id:"r_"+now(),userId:u.id,user:u.name||u.username,title:$("reqTitle").value.trim(),text:$("reqText").value.trim(),file:fileData,status:"pending",date:now()});save();e.target.reset();toast("Request terkirim ke admin!")});
function readFile(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
function renderProfile(){const u=user();if(!u){showPage("home");return}$("profileUsername").value=u.username;$("profileName").value=u.name||"";$("profileAvatar").value=u.avatar||"";$("profileHeading").textContent=u.name||u.username;$("profileAvatarPreview").innerHTML=u.avatar?`<img src="${escape(u.avatar)}" alt="">`:escape((u.name||u.username)[0].toUpperCase())}
$("profileForm").addEventListener("submit",e=>{e.preventDefault();const u=user();if(!u)return;u.name=$("profileName").value.trim()||u.username;u.avatar=$("profileAvatar").value.trim();save();renderProfile();toast("Profile disimpan")});
$("passwordForm").addEventListener("submit",e=>{e.preventDefault();const u=user();if($("oldPassword").value!==u.password)return toast("Password lama salah.",true);if($("newPassword").value.length<6)return toast("Password minimal 6 karakter.",true);u.password=$("newPassword").value;save();e.target.reset();toast("Password berhasil diubah")});
function requireAdmin(){if(user()?.role!=="admin"){toast("Akses admin ditolak.",true);showPage("home");return false}return true}
function renderCategoryChoices(selected=[]){const box=$("categoryChoices");box.innerHTML=CATEGORIES.map(c=>`<label class="check-item"><input type="checkbox" value="${escape(c)}" ${selected.includes(c)?"checked":""}> <span>${escape(c)}</span></label>`).join("");const update=()=>{const vals=selectedCategories();$("categorySummary").textContent=vals.length?`${vals.length} kategori dipilih`:"Pilih kategori"};box.querySelectorAll("input").forEach(x=>x.addEventListener("change",update));update()}
function selectedCategories(){return [...document.querySelectorAll("#categoryChoices input:checked")].map(x=>x.value)}
function resetAddonForm(){ $("addonForm").reset();$("editAddonId").value="";$("addonFormTitle").textContent="Tambah Addon";$("releaseHelp").textContent="Untuk update, pilih addon yang sudah ada lalu masukkan versi + path file baru. Versi lama tidak akan dihapus.";renderCategoryChoices([]);$("addonForm").classList.add("hidden")}
function renderAdmin(){if(!requireAdmin())return;$("stats").innerHTML=`<div class="stat"><span class="muted">Addons</span><b>${db.addons.length}</b></div><div class="stat"><span class="muted">Users</span><b>${db.users.length}</b></div><div class="stat"><span class="muted">Requests</span><b>${db.requests.filter(r=>r.status==="pending").length}</b></div><div class="stat"><span class="muted">Downloads</span><b>${db.addons.reduce((n,a)=>n+(a.downloads||0),0)}</b></div>`;renderAdminAddons();renderAdminRequests();renderAdminUsers();renderCategoryChoices([]);$("addonForm").classList.add("hidden")}
function renderAdminAddons(){$("adminAddonList").innerHTML=sortedAddons().map(a=>{const r=latestRelease(a);return `<div class="admin-item"><div><b>${escape(a.name)}</b><div class="tags">${(a.tags||[]).map(t=>`<span class="tag">${escape(t)}</span>`).join("")}</div><div class="muted">Terbaru: v${escape(r?.version||"-")} · MC ${escape(r?.mcVersion||"-")} · ${a.releases.length} versi · update ${new Date(a.updatedAt||a.createdAt).toLocaleDateString()}</div></div><div class="actions"><button class="btn small ghost" onclick="editAddon('${a.id}')">Update Addon</button><button class="btn small danger" onclick="deleteAddon('${a.id}')">Delete</button></div></div>`}).join("")||"<p class='muted'>Belum ada addon.</p>"}
$("showAddonForm").addEventListener("click",()=>{resetAddonForm();$("addonForm").classList.remove("hidden");window.scrollTo({top:250,behavior:"smooth"})});
$("addonForm").addEventListener("submit",e=>{e.preventDefault();if(!requireAdmin())return;const id=$("editAddonId").value,old=db.addons.find(a=>a.id===id),name=$("addonName").value.trim(),tags=selectedCategories(),mcVersion=$("addonVersion").value.trim(),release=$("addonRelease").value.trim()||"1.0.0",filePath=$("addonFilePath").value.trim(),image=$("addonImage").value.trim();if(!name||!mcVersion||!release||!filePath||!image)return toast("Nama, versi, path file, dan thumbnail wajib diisi.",true);if(!tags.length)return toast("Pilih minimal satu kategori/tag.",true);const stamp=now(),rel={id:"rel_"+stamp+"_"+Math.random().toString(36).slice(2,6),version:release,mcVersion,filePath:filePath.replace(/^\//,""),changelog:$("addonChangelog").value.trim(),createdAt:stamp};if(old){old.name=name;old.tags=tags;old.image=image.replace(/^\//,"");old.video=$("addonVideo").value.trim();old.author=$("addonAuthor").value.trim()||"Fuyuko Team";old.description=$("addonDescription").value.trim();old.features=$("addonFeatures").value.split(",").map(x=>x.trim()).filter(Boolean);old.updatedAt=stamp;old.releases=old.releases||[];old.releases.unshift(rel)}else{db.addons.push({id:"a_"+stamp+"_"+Math.random().toString(36).slice(2,7),name,tags,image:image.replace(/^\//,""),video:$("addonVideo").value.trim(),author:$("addonAuthor").value.trim()||"Fuyuko Team",description:$("addonDescription").value.trim(),features:$("addonFeatures").value.split(",").map(x=>x.trim()).filter(Boolean),downloads:0,comments:[],ratings:{},createdAt:stamp,updatedAt:stamp,releases:[rel]})}save();resetAddonForm();renderAdmin();renderFeatured();toast(old?`Versi v${release} ditambahkan. Versi lama tetap tersedia.`:`Addon ${name} berhasil dibuat.`)});
$("cancelEdit").addEventListener("click",resetAddonForm);
window.editAddon=id=>{const a=db.addons.find(x=>x.id===id);if(!a)return;const r=latestRelease(a);$("editAddonId").value=id;$("addonFormTitle").textContent="Tambah Versi / Update Addon";$("addonName").value=a.name;$("addonImage").value=a.image||"";$("addonVideo").value=a.video||"";$("addonAuthor").value=a.author||"";$("addonDescription").value=a.description||"";$("addonFeatures").value=(a.features||[]).join(", ");$("addonVersion").value=r?.mcVersion||"";$("addonRelease").value="";$("addonFilePath").value="";$("addonChangelog").value="";renderCategoryChoices(a.tags||[]);$("releaseHelp").textContent=`${a.name} punya ${a.releases.length} versi. Masukkan versi baru + path file baru. Versi lama tetap tersedia.`;$("addonForm").classList.remove("hidden");window.scrollTo({top:250,behavior:"smooth"})};
window.deleteAddon=id=>{if(!requireAdmin()||!confirm("Hapus addon ini beserta semua versinya?"))return;db.addons=db.addons.filter(a=>a.id!==id);save();renderAdmin();renderFeatured();toast("Addon dihapus")};
function renderAdminRequests(){$("adminRequestList").innerHTML=db.requests.length?db.requests.slice().reverse().map(r=>`<div class="admin-item"><div><b>${escape(r.title)}</b><div class="muted">${escape(r.user)} · ${new Date(r.date).toLocaleString()} · status: ${escape(r.status)}</div><p>${escape(r.text)}</p>${r.file?`<div class="muted">File: ${escape(r.file.name)} (${Math.round(r.file.size/1024)} KB)</div><button class="text-btn" onclick="downloadRequestFile('${r.id}')">Download file request</button>`:""}</div><div class="actions"><button class="btn small" onclick="setRequest('${r.id}','accepted')">Accept</button><button class="btn small ghost" onclick="setRequest('${r.id}','rejected')">Reject</button><button class="btn small danger" onclick="deleteRequest('${r.id}')">Delete</button></div></div>`).join(""):"<p class='muted'>Belum ada request.</p>"}
window.downloadRequestFile=id=>{const r=db.requests.find(x=>x.id===id);if(!r?.file?.data)return;const a=document.createElement("a");a.href=r.file.data;a.download=r.file.name;document.body.appendChild(a);a.click();a.remove()};
window.setRequest=(id,status)=>{const r=db.requests.find(x=>x.id===id);if(!r)return;r.status=status;save();renderAdminRequests();toast("Status request diperbarui")};
window.deleteRequest=id=>{db.requests=db.requests.filter(x=>x.id!==id);save();renderAdminRequests();toast("Request dihapus")};
function renderAdminUsers(){$("adminUserList").innerHTML=db.users.map(u=>`<div class="admin-item"><div class="user-line"><div class="avatar">${u.avatar?`<img src="${escape(u.avatar)}">`:escape((u.name||u.username)[0].toUpperCase())}</div><div><b>${escape(u.name||u.username)}</b><div class="muted">@${escape(u.username)} · role: ${escape(u.role)}</div></div></div><div class="actions">${u.id!=="u_admin"&&u.id!==user()?.id?`<button class="btn small ghost" onclick="toggleAdmin('${u.id}')">${u.role==="admin"?"Jadikan User":"Jadikan Admin"}</button>`:""}</div></div>`).join("")}
window.toggleAdmin=id=>{if(!requireAdmin())return;const u=db.users.find(x=>x.id===id);if(!u)return;u.role=u.role==="admin"?"user":"admin";save();renderAdminUsers();updateNav();toast(`Role ${u.username} sekarang ${u.role}`)};
document.querySelectorAll(".admin-tabs .tab").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".admin-tabs .tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".admin-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.tab).classList.add("active")}));
renderCategoryChoices([]);updateNav();renderFeatured();renderRequestPage();
