const CATEGORIES=["From Marketplace","Server Utility","Redstone","Farming","PVP","Combat","Survival","Utility","World Generation","Mobs","Weapons","Armor","Tools","Magic","Economy","Minigame","UI","Shader","Texture","Optimization","Adventure","Building","Decoration","Transportation","Other"];
const cfg=window.FUYUKO_SUPABASE||{};
const backendReady=Boolean(window.supabase&&cfg.url&&cfg.anonKey&&!/YOUR-PROJECT|YOUR-PUBLISHABLE/i.test(cfg.url+cfg.anonKey));
const sb=backendReady?window.supabase.createClient(cfg.url,cfg.anonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}):null;
let currentUser=null,currentProfile=null,currentAddon=null,selectedRating=0,publicRequestsCache=[],myRequestsCache=[];
const $=id=>document.getElementById(id),escapeHTML=(s="")=>String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));
const normalizePath=p=>String(p||"").trim().replace(/^\/+/,"");
const assetPath=p=>{const v=normalizePath(p);if(!v)return"";if(/^https?:\/\//i.test(v))return v;return v;};
const now=()=>Date.now();
function toast(msg,error=false){const t=$("toast");t.textContent=msg;t.className="toast show"+(error?" error":"");clearTimeout(toast.t);toast.t=setTimeout(()=>{t.textContent="";t.className="toast"},2600)}
function showSetup(){
  const b=$("setupBanner");
  if(backendReady){b.classList.add("hidden");return}
  b.classList.remove("hidden");b.innerHTML='<b>Backend belum dikonfigurasi.</b> Isi <code>supabase-config.js</code> dengan URL + publishable/anon key project Supabase, lalu refresh website.';
}
function requireBackend(){if(!backendReady){toast("Supabase belum dikonfigurasi.",true);return false}return true}
function requireAuth(){if(!currentUser){toast("Login diperlukan.",true);openAuth();return false}return true}
function requireAdmin(){if(!currentProfile||currentProfile.role!=="admin"){toast("Akses admin diperlukan.",true);return false}return true}
function openAuth(tab="login"){$("authModal").classList.remove("hidden");document.querySelectorAll("[data-auth]").forEach(x=>x.classList.toggle("active",x.dataset.auth===tab));$("loginForm").classList.toggle("hidden",tab!=="login");$("registerForm").classList.toggle("hidden",tab!=="register")}
function showPage(id){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));const p=$(id);if(!p)return;p.classList.add("active");$("nav").classList.remove("open");window.scrollTo(0,0);if(id==="home")renderFeatured();if(id==="addons")loadAddons();if(id==="requests")loadRequestsPage();if(id==="profile")renderProfile();if(id==="admin")loadAdmin();if(id==="detail"&&currentAddon)renderDetail(currentAddon)}
document.addEventListener("click",e=>{const x=e.target.closest("[data-page]");if(x){e.preventDefault();showPage(x.dataset.page)}});
$("menuBtn").onclick=()=>$("nav").classList.toggle("open");
$("loginBtn").onclick=()=>openAuth();
$("closeAuth").onclick=()=>$("authModal").classList.add("hidden");
document.querySelectorAll("[data-auth]").forEach(b=>b.onclick=()=>openAuth(b.dataset.auth));
$("logoutBtn").onclick=async()=>{if(sb)await sb.auth.signOut();currentUser=null;currentProfile=null;updateNav();showPage("home");toast("Berhasil logout")};
function updateNav(){const ok=!!currentUser;document.querySelectorAll(".auth-only").forEach(x=>x.classList.toggle("hidden",!ok));document.querySelectorAll(".admin-only").forEach(x=>x.classList.toggle("hidden",currentProfile?.role!=="admin"));$("loginBtn").classList.toggle("hidden",ok);$("logoutBtn").classList.toggle("hidden",!ok);document.querySelectorAll(".auth-required-action").forEach(x=>x.classList.toggle("hidden",!ok))}
function usernameEmail(username){return `${String(username).trim().toLowerCase()}@login.fuyuko.web.id`}
function formatDate(v){return v?new Date(v).toLocaleString("id-ID",{dateStyle:"medium",timeStyle:"short"}):"-"}
function initials(profile){return String(profile?.display_name||profile?.username||"F").slice(0,1).toUpperCase()}
function avatarHTML(profile,size=""){const cls=`avatar ${size}`;return profile?.avatar_url?`<div class="${cls}"><img src="${escapeHTML(profile.avatar_url)}" alt=""></div>`:`<div class="${cls}">${escapeHTML(initials(profile))}</div>`}
function starHTML(value=0){let html="";for(let i=0;i<5;i++){const fill=Math.max(0,Math.min(1,value-i));html+=`<span class="star" style="--fill:${fill*100}%">★</span>`}return `<span class="five-stars" aria-label="${Number(value).toFixed(1)}/5">${html}</span>`}
function ratingPickerHTML(){return `<div class="rating-picker">${[0,1,2,3,4].map(i=>`<span class="picker-star"><span>★</span><button class="half-btn left" onclick="setRating(${i+.5})" aria-label="${i+.5} stars"></button><button class="half-btn right" onclick="setRating(${i+1})" aria-label="${i+1} stars"></button></span>`).join("")}</div>`}
window.setRating=v=>{selectedRating=v;const el=$("ratingPicker");if(el)el.innerHTML=ratingPickerHTML()+`<span class="rating-value">${v.toFixed(1)}/5</span>`;renderRatingPickerFill()};
function renderRatingPickerFill(){document.querySelectorAll("#ratingPicker .picker-star").forEach((el,i)=>{const fill=Math.max(0,Math.min(1,selectedRating-i));el.style.setProperty("--fill",`${fill*100}%`)})}
async function getProfileById(id){if(!sb||!id)return null;const {data,error}=await sb.from("profiles").select("id,username,display_name,avatar_url,role,created_at").eq("id",id).single();if(error)return null;return data}
async function refreshUser(session){currentUser=session?.user||null;currentProfile=currentUser?await getProfileById(currentUser.id):null;updateNav();if(currentProfile)renderProfile();}
if(sb){sb.auth.getSession().then(({data})=>refreshUser(data.session));sb.auth.onAuthStateChange((_e,session)=>refreshUser(session));}
showSetup();

async function handleLogin(e){e.preventDefault();if(!requireBackend())return;const username=$("loginUser").value.trim();const password=$("loginPass").value;if(!username||!password)return;const {error}=await sb.auth.signInWithPassword({email:usernameEmail(username),password});if(error){toast(error.message||"Login gagal.",true);return}$("authModal").classList.add("hidden");e.target.reset();toast("Login berhasil");}
async function handleRegister(e){e.preventDefault();if(!requireBackend())return;const username=$("regUser").value.trim();const password=$("regPass").value;const displayName=$("regName").value.trim()||username;if(!/^[a-zA-Z0-9_.-]{3,24}$/.test(username))return toast("Username hanya boleh huruf, angka, _, ., -",true);const {data,error}=await sb.auth.signUp({email:usernameEmail(username),password,options:{data:{username,display_name:displayName}}});if(error){toast(error.message||"Register gagal.",true);return}if(!data.session){toast("Akun dibuat. Aktifkan auto-confirm email di Supabase Auth agar login tanpa Gmail bisa langsung dipakai.",true)}else toast("Akun berhasil dibuat");$("authModal").classList.add("hidden");e.target.reset()}
$("loginForm").onsubmit=handleLogin;$("registerForm").onsubmit=handleRegister;

function sortAddons(arr){return [...arr].sort((a,b)=>new Date(b.updated_at||b.created_at)-new Date(a.updated_at||a.created_at))}
function latestRelease(a){return (a.addon_releases||[]).slice().sort((x,y)=>new Date(y.created_at)-new Date(x.created_at))[0]||null}
function avgRating(a){const vals=(a._ratings||[]).map(r=>Number(r.rating));return vals.length?Math.round(vals.reduce((s,n)=>s+n,0)/vals.length*2)/2:0}
function isNewAddon(a){return Date.now()-new Date(a.updated_at||a.created_at).getTime()<14*86400000}
function addonCard(a){const r=latestRelease(a),src=assetPath(a.image_path);const tags=(a.tags||[]).slice(0,3).map(t=>`<span class="tag">${escapeHTML(t)}</span>`).join("");const thumb=src?`<img src="${escapeHTML(src)}" alt="${escapeHTML(a.name)}" onerror="this.style.display='none';this.parentElement.classList.add('broken-thumb')">`:`<span class="placeholder">FW</span>`;return `<article class="card"><div class="thumb">${thumb}<span class="image-fallback">FW</span>${isNewAddon(a)?'<span class="update-badge">UPDATE BARU</span>':''}</div><div class="card-body"><div class="tags">${tags}</div><h3>${escapeHTML(a.name)}</h3><p class="muted clamp">${escapeHTML(a.description||"")}</p><div class="rating">${starHTML(avgRating(a))}<span class="muted">${avgRating(a).toFixed(1)} (${a._ratings?.length||0})</span></div><div class="tags"><span class="tag">MC ${escapeHTML(r?.mc_version||"-")}</span><span class="tag">v${escapeHTML(r?.version||"-")}</span></div><div class="card-footer"><span class="muted">${a.downloads||0} downloads</span><button class="btn small" onclick="openAddon('${a.id}')">Details</button></div></div></article>`}
async function fetchAddons(){if(!sb)return[];const {data,error}=await sb.from("addons").select("*, addon_releases(*)").order("updated_at",{ascending:false});if(error){toast(error.message,true);return[]}if(!data.length)return[];const ids=data.map(x=>x.id);const [{data:ratings}]=await Promise.all([sb.from("ratings").select("addon_id,rating").in("addon_id",ids)]);const by={};(ratings||[]).forEach(r=>(by[r.addon_id]??=[]).push(r));return data.map(a=>({...a,_ratings:by[a.id]||[]}))}
async function renderFeatured(){const list=sortAddons(await fetchAddons());$("featuredGrid").innerHTML=list.slice(0,4).map(addonCard).join("")||"<p class='muted'>Belum ada addon.</p>"}
async function loadAddons(){const list=await fetchAddons();const cats=[...new Set(list.flatMap(a=>a.tags||[]))].sort();const vers=[...new Set(list.flatMap(a=>(a.addon_releases||[]).map(r=>r.mc_version).filter(Boolean)))].sort();$("categoryFilter").innerHTML='<option value="">All categories</option>'+cats.map(x=>`<option>${escapeHTML(x)}</option>`).join("");$("versionFilter").innerHTML='<option value="">All versions</option>'+vers.map(x=>`<option>${escapeHTML(x)}</option>`).join("");renderAddonResults(list)}
function renderAddonResults(list){const q=$("searchInput").value.trim().toLowerCase(),c=$("categoryFilter").value,v=$("versionFilter").value;const filtered=sortAddons(list).filter(a=>{const text=[a.name,a.description,(a.tags||[]).join(" "),...(a.addon_releases||[]).flatMap(r=>[r.version,r.mc_version,r.changelog])].join(" ").toLowerCase();return(!q||text.includes(q))&&(!c||(a.tags||[]).includes(c))&&(!v||(a.addon_releases||[]).some(r=>r.mc_version===v))});$("addonGrid").innerHTML=filtered.map(addonCard).join("")||"<p class='muted'>Addon tidak ditemukan.</p>"}
["searchInput","categoryFilter","versionFilter"].forEach(id=>$(id).addEventListener("input",async()=>renderAddonResults(await fetchAddons())));

async function openAddon(id){if(!sb)return;const {data,error}=await sb.from("addons").select("*, addon_releases(*)").eq("id",id).single();if(error){toast(error.message,true);return}const [{data:ratings},{data:comments}]=await Promise.all([sb.from("ratings").select("user_id,rating").eq("addon_id",id),sb.from("comments").select("id,addon_id,user_id,parent_id,body,created_at,profiles(id,username,display_name,avatar_url)").eq("addon_id",id).order("created_at",{ascending:true})]);data._ratings=ratings||[];data._comments=comments||[];currentAddon=data;showPage("detail");renderDetail(data)}
function renderDetail(a){const avg=avgRating(a),mine=a._ratings?.find(x=>x.user_id===currentUser?.id)?.rating||0;a._comments=a._comments||[];const releases=(a.addon_releases||[]).slice().sort((x,y)=>new Date(y.created_at)-new Date(x.created_at));$("detailContent").innerHTML=`<div class="detail-hero"><div class="detail-thumb">${assetPath(a.image_path)?`<img src="${escapeHTML(assetPath(a.image_path))}" alt="">`:'FW'}</div><div><div class="tags">${(a.tags||[]).map(t=>`<span class="tag">${escapeHTML(t)}</span>`).join("")}</div><h1>${escapeHTML(a.name)}</h1><p class="muted">${escapeHTML(a.description||"")}</p><div class="rating">${starHTML(avg)}<b>${avg.toFixed(1)}</b><span class="muted">${a._ratings?.length||0} rating</span></div><p class="muted">Author: ${escapeHTML(a.author||"Fuyuko Team")} · ${a.downloads||0} downloads</p></div></div>
<div class="detail-grid"><div class="panel"><h2>Features</h2><div class="feature-list">${(a.features||[]).map(x=>`<span class="feature-pill">${escapeHTML(x)}</span>`).join("")||'<span class="muted">Belum ada data fitur.</span>'}</div></div><div class="panel"><h2>Versions</h2><div class="release-list">${releases.map(r=>`<div class="release-public"><div><b>v${escapeHTML(r.version)}</b><span class="tag">MC ${escapeHTML(r.mc_version||"-")}</span><p class="muted">${escapeHTML(r.changelog||"Tidak ada changelog")}</p></div><button class="btn small" onclick="downloadAddon('${a.id}','${r.id}')">Download</button></div>`).join("")}</div></div></div>
<div class="panel"><h2>Rating</h2>${currentUser?`<div id="ratingPicker">${ratingPickerHTML()}</div><span class="rating-value">Rating kamu: ${mine?Number(mine).toFixed(1)+"/5":"belum memberi rating"}</span><button class="btn small" onclick="saveRating('${a.id}')">Simpan Rating</button>`:'<p class="muted">Login untuk memberi rating.</p>'}</div>
<div class="panel comments-panel"><div class="panel-head"><div><h2>Comments</h2><p class="muted">Balasan dapat dibuka/tutup agar tidak memenuhi halaman.</p></div></div><div class="comment-list">${renderCommentTree(a._comments)}</div>${currentUser?`<div class="comment-compose"><textarea id="addonCommentText" class="input" rows="3" placeholder="Tulis komentar..."></textarea><button class="btn" onclick="postAddonComment('${a.id}')">Komentar</button></div>`:'<p class="muted">Login untuk berkomentar.</p>'}</div>`;selectedRating=mine||0;setTimeout(renderRatingPickerFill,0)}
function renderCommentTree(comments){const roots=comments.filter(c=>!c.parent_id);const children=id=>comments.filter(c=>c.parent_id===id);const item=c=>{const kids=children(c.id);return `<div class="comment-item"><div class="comment-row">${avatarHTML(c.profiles||{} )}<div class="comment-main"><div class="comment-meta"><b>${escapeHTML(c.profiles?.display_name||c.profiles?.username||"User")}</b><span>@${escapeHTML(c.profiles?.username||"user")}</span><time>${formatDate(c.created_at)}</time></div><p>${escapeHTML(c.body)}</p><button class="text-btn" onclick="toggleReplyBox('${c.id}')">Reply</button>${kids.length?`<button class="text-btn" onclick="toggleReplies('${c.id}')">Balasan (${kids.length})</button>`:""}<div id="replybox_${c.id}" class="reply-box hidden"><textarea class="input" id="replytext_${c.id}" rows="2" placeholder="Balas komentar..."></textarea><button class="btn small" onclick="replyAddonComment('${currentAddon.id}','${c.id}')">Balas</button></div><div id="replies_${c.id}" class="replies hidden">${kids.map(item).join("")}</div></div></div></div>`};return roots.map(item).join("")||'<p class="muted">Belum ada komentar.</p>'}
window.toggleReplyBox=id=>$("replybox_"+id)?.classList.toggle("hidden");window.toggleReplies=id=>$("replies_"+id)?.classList.toggle("hidden");
window.postAddonComment=async addonId=>{if(!requireAuth())return;const body=$("addonCommentText").value.trim();if(!body)return;const {error}=await sb.from("comments").insert({addon_id:addonId,user_id:currentUser.id,body});if(error)return toast(error.message,true);$("addonCommentText").value="";await openAddon(addonId);toast("Komentar ditambahkan")}
window.replyAddonComment=async(addonId,parentId)=>{if(!requireAuth())return;const el=$("replytext_"+parentId),body=el?.value.trim();if(!body)return;const {error}=await sb.from("comments").insert({addon_id:addonId,user_id:currentUser.id,parent_id:parentId,body});if(error)return toast(error.message,true);await openAddon(addonId);toast("Balasan ditambahkan")}
window.saveRating=async addonId=>{if(!requireAuth())return;if(selectedRating<.5)return toast("Pilih 0.5 sampai 5 bintang.",true);const {error}=await sb.from("ratings").upsert({addon_id:addonId,user_id:currentUser.id,rating:selectedRating});if(error)return toast(error.message,true);await openAddon(addonId);toast("Rating tersimpan")}
window.downloadAddon=async(addonId,releaseId)=>{const {data,error}=await sb.from("addon_releases").select("file_path").eq("id",releaseId).single();if(error)return toast(error.message,true);const path=data.file_path;if(!path)return toast("File belum disiapkan.",true);if(sb){sb.rpc("increment_download",{p_addon_id:addonId}).catch(()=>{});}if(/^https?:\/\//i.test(path))window.open(path,"_blank");else{const a=document.createElement("a");a.href=assetPath(path);a.target="_blank";a.rel="noopener";document.body.appendChild(a);a.click();a.remove()};await openAddon(addonId)}

function selectedCategories(){return [...document.querySelectorAll("#categoryChoices input:checked")].map(x=>x.value)}
function renderCategoryChoices(selected=[]){$("categoryChoices").innerHTML=CATEGORIES.map(c=>`<label class="check-chip"><input type="checkbox" value="${escapeHTML(c)}" ${selected.includes(c)?"checked":""}><span>${escapeHTML(c)}</span></label>`).join("");updateCategorySummary()}
function updateCategorySummary(){const s=selectedCategories();$("categorySummary").textContent=s.length?`${s.length} kategori dipilih`:"Pilih kategori"}
$("categoryChoices").addEventListener("change",updateCategorySummary);
document.querySelectorAll(".editor-toggle").forEach(b=>b.onclick=()=>{$(b.dataset.toggle)?.classList.toggle("collapsed");b.classList.toggle("open")});

function resetAddonForm(){
  $("addonForm").classList.add("hidden");$("editAddonId").value="";$("addonFormTitle").textContent="Tambah Addon Baru";$("addonFormHint").textContent="Info dasar addon dan file versi pertama.";
  ["addonName","addonImage","addonVideo","addonAuthor","addonDescription","addonFeatures","addonRelease","addonVersion","addonFilePath","addonChangelog"].forEach(id=>$(id).value="");renderCategoryChoices([]);$("releaseEditorSection").classList.add("hidden");$("initialReleaseSection").classList.remove("hidden");$("initialReleaseSection").querySelector(".editor-body").classList.remove("collapsed");
}
$("showAddonForm").onclick=()=>{resetAddonForm();$("addonForm").classList.remove("hidden");window.scrollTo({top:220,behavior:"smooth"})};
$("saveAddonInfoBtn").onclick=async()=>{if(!requireAdmin())return;const id=$("editAddonId").value;if(!id)return toast("Buat addon dulu.",true);const payload={name:$("addonName").value.trim(),tags:selectedCategories(),image_path:normalizePath($("addonImage").value),video_url:$("addonVideo").value.trim()||null,author:$("addonAuthor").value.trim()||"Fuyuko Team",description:$("addonDescription").value.trim(),features:$("addonFeatures").value.split(",").map(x=>x.trim()).filter(Boolean),updated_at:new Date().toISOString()};if(!payload.name||!payload.description||!payload.image_path||!payload.tags.length)return toast("Nama, deskripsi, thumbnail, dan minimal satu tag wajib.",true);const {error}=await sb.from("addons").update(payload).eq("id",id);if(error)return toast(error.message,true);await loadAdmin();await renderFeatured();toast("Info addon disimpan")}
$("createAddonBtn").onclick=async()=>{if(!requireAdmin())return;const payload={name:$("addonName").value.trim(),tags:selectedCategories(),image_path:normalizePath($("addonImage").value),video_url:$("addonVideo").value.trim()||null,author:$("addonAuthor").value.trim()||"Fuyuko Team",description:$("addonDescription").value.trim(),features:$("addonFeatures").value.split(",").map(x=>x.trim()).filter(Boolean),created_by:currentUser.id};const release={version:$("addonRelease").value.trim()||"1.0.0",mc_version:$("addonVersion").value.trim(),file_path:normalizePath($("addonFilePath").value),changelog:$("addonChangelog").value.trim()};if(!payload.name||!payload.description||!payload.image_path||!payload.tags.length||!release.mc_version||!release.file_path)return toast("Lengkapi info addon dan file versi pertama.",true);const {data,error}=await sb.from("addons").insert(payload).select().single();if(error)return toast(error.message,true);const {error:re}=await sb.from("addon_releases").insert({...release,addon_id:data.id});if(re){await sb.from("addons").delete().eq("id",data.id);return toast(re.message,true)}resetAddonForm();await loadAdmin();await renderFeatured();toast("Addon berhasil dibuat")}
$("addVersionBtn").onclick=()=>{if(!requireAdmin())return;$("newVersionForm").classList.remove("hidden");$("newReleaseVersion").focus()};
$("cancelNewVersionBtn").onclick=()=>$("newVersionForm").classList.add("hidden");
$("saveNewVersionBtn").onclick=async()=>{if(!requireAdmin())return;const id=$("editAddonId").value;const version=$("newReleaseVersion").value.trim(),mc=$("newReleaseMc").value.trim(),path=normalizePath($("newReleasePath").value),changelog=$("newReleaseChangelog").value.trim();if(!id||!version||!mc||!path)return toast("Versi, versi Minecraft, dan path file wajib diisi.",true);const {error}=await sb.from("addon_releases").insert({addon_id:id,version,mc_version:mc,file_path:path,changelog});if(error)return toast(error.message,true);$("newVersionForm").classList.add("hidden");["newReleaseVersion","newReleaseMc","newReleasePath","newReleaseChangelog"].forEach(x=>$(x).value="");await openAdminAddon(id);toast("File versi baru ditambahkan")};
window.deleteRelease=async(id)=>{if(!requireAdmin())return;if(!confirm("Hapus file versi ini dari database?"))return;const {data}=await sb.from("addon_releases").select("id,addon_id").eq("id",id).single();if(!data)return;const {error}=await sb.from("addon_releases").delete().eq("id",id);if(error)return toast(error.message,true);await openAdminAddon(data.addon_id);toast("File versi dihapus")}
window.deleteAddon=async id=>{if(!requireAdmin()||!confirm("Hapus addon beserta semua versi dan komentarnya?"))return;const {error}=await sb.from("addons").delete().eq("id",id);if(error)return toast(error.message,true);resetAddonForm();await loadAdmin();await renderFeatured();toast("Addon dihapus")}
window.openAdminAddon=async id=>{if(!requireAdmin())return;const {data,error}=await sb.from("addons").select("*, addon_releases(*)").eq("id",id).single();if(error)return toast(error.message,true);$("editAddonId").value=id;$("addonFormTitle").textContent=`Kelola / Update: ${data.name}`;$("addonFormHint").textContent="Editor dibuka hanya setelah menekan Kelola/Update.";$("addonName").value=data.name;$("addonImage").value=data.image_path||"";$("addonVideo").value=data.video_url||"";$("addonAuthor").value=data.author||"";$("addonDescription").value=data.description||"";$("addonFeatures").value=(data.features||[]).join(", ");renderCategoryChoices(data.tags||[]);$("initialReleaseSection").classList.add("hidden");$("releaseEditorSection").classList.remove("hidden");$("newVersionForm").classList.add("hidden");renderVersionManager(data);$("addonForm").classList.remove("hidden");$("addonForm").scrollIntoView({behavior:"smooth",block:"start"})}
function renderVersionManager(a){const rows=(a.addon_releases||[]).slice().sort((x,y)=>new Date(y.created_at)-new Date(x.created_at)).map(r=>`<div class="release-admin"><div><div><b>v${escapeHTML(r.version)}</b> <span class="tag">MC ${escapeHTML(r.mc_version||"-")}</span></div><p class="muted">${escapeHTML(r.changelog||"Tidak ada changelog")}</p><code>${escapeHTML(r.file_path||"-")}</code></div><button class="btn small danger" onclick="deleteRelease('${r.id}')">Hapus file</button></div>`).join("");$("versionManager").innerHTML=rows||"<p class='muted'>Belum ada file versi.</p>"}

async function loadAdmin(){if(!requireAdmin())return;const addons=await fetchAddons();const [{data:requests},{data:users}]=await Promise.all([sb.from("requests").select("*,profiles(username,display_name)").order("created_at",{ascending:false}),sb.from("profiles").select("id,username,display_name,avatar_url,role,created_at").order("created_at",{ascending:true})]);$("stats").innerHTML=`<div class="stat"><b>${addons.length}</b><span>Addons</span></div><div class="stat"><b>${requests?.length||0}</b><span>Requests</span></div><div class="stat"><b>${users?.length||0}</b><span>Users</span></div>`;$("adminAddonList").innerHTML=sortAddons(addons).map(a=>{const r=latestRelease(a);return `<div class="admin-addon-card"><div class="admin-addon-main">${a.image_path?`<img src="${escapeHTML(assetPath(a.image_path))}" alt="">`:'<div class="admin-mini-placeholder">FW</div>'}<div><h3>${escapeHTML(a.name)}</h3><p class="muted">Latest v${escapeHTML(r?.version||"-")} · MC ${escapeHTML(r?.mc_version||"-")} · ${(a.addon_releases||[]).length} file</p></div></div><div class="actions"><button class="btn small" onclick="openAdminAddon('${a.id}')">Kelola / Update</button><button class="btn small danger" onclick="deleteAddon('${a.id}')">Hapus</button></div></div>`}).join("")||"<p class='muted'>Belum ada addon.</p>";renderAdminRequests(requests||[]);renderAdminUsers(users||[])}
function renderAdminUsers(users){$("adminUserList").innerHTML=(users||[]).map(u=>`<div class="admin-item"><div class="user-line">${avatarHTML(u)}<div><b>${escapeHTML(u.display_name||u.username)}</b><div class="muted">@${escapeHTML(u.username)} · ${escapeHTML(u.role)}</div></div></div>${u.id!==currentUser?.id?`<button class="btn small ghost" onclick="toggleAdmin('${u.id}','${u.role==='admin'?'user':'admin'}')">${u.role==='admin'?'Jadikan User':'Jadikan Admin'}</button>`:''}</div>`).join("")||"<p class='muted'>Belum ada user.</p>"}
window.toggleAdmin=async(id,role)=>{if(!requireAdmin())return;const {error}=await sb.rpc("set_user_role",{p_user_id:id,p_role:role});if(error)return toast(error.message,true);await loadAdmin();toast("Role diperbarui")}

document.querySelectorAll(".admin-tabs .tab").forEach(b=>b.onclick=async()=>{document.querySelectorAll(".admin-tabs .tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".admin-tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$(b.dataset.tab).classList.add("active");if(b.dataset.tab==='manageAddons')await loadAdmin();if(b.dataset.tab==='manageRequests')await loadAdminRequests();if(b.dataset.tab==='manageUsers')await loadAdmin()});

function commentThread(items,type,id){const roots=items.filter(x=>!x.parent_id),children=p=>items.filter(x=>x.parent_id===p);const draw=x=>{const kids=children(x.id);return `<div class="thread-item">${avatarHTML(x.profiles||{})}<div class="thread-body"><div class="comment-meta"><b>${escapeHTML(x.profiles?.display_name||x.profiles?.username||"User")}</b><span>@${escapeHTML(x.profiles?.username||"user")}</span><time>${formatDate(x.created_at)}</time></div><p>${escapeHTML(x.body)}</p><div class="thread-tools">${currentUser?`<button class="text-btn" onclick="toggleRequestReply('${id}','${x.id}')">Reply</button>`:""}${kids.length?`<button class="text-btn" onclick="toggleRequestReplies('${x.id}')">Balasan (${kids.length})</button>`:""}</div>${currentUser?`<div id="requestreply_${x.id}" class="reply-box hidden"><textarea class="input" id="requestreplytext_${x.id}" rows="2" placeholder="Balas..."></textarea><button class="btn small" onclick="replyRequest('${id}','${x.id}')">Balas</button></div>`:""}<div id="requestreplies_${x.id}" class="replies hidden">${kids.map(draw).join("")}</div></div></div>`};return roots.map(draw).join("")||'<p class="muted">Belum ada komentar.</p>'}
window.toggleRequestReply=id=>$("requestreply_"+id)?.classList.toggle("hidden");window.toggleRequestReplies=id=>$("requestreplies_"+id)?.classList.toggle("hidden");

async function fetchRequests(scope="public"){if(!sb)return[];let q=sb.from("requests").select("*,profiles(username,display_name,avatar_url)").order("created_at",{ascending:false});if(scope==='public')q=q.eq("visibility","public");else if(scope==='mine')q=q.eq("user_id",currentUser.id);const {data,error}=await q;if(error){toast(error.message,true);return[]}const ids=(data||[]).map(r=>r.id);const [{data:supports},{data:comments}]=ids.length?await Promise.all([sb.from("request_supports").select("request_id,user_id").in("request_id",ids),sb.from("request_comments").select("id,request_id,user_id,parent_id,body,created_at,profiles(username,display_name,avatar_url)").in("request_id",ids).order("created_at",{ascending:true})]):[{data:[]},{data:[]}];const supMap={};(supports||[]).forEach(s=>(supMap[s.request_id]??=[]).push(s.user_id));const comMap={};(comments||[]).forEach(c=>(comMap[c.request_id]??=[]).push(c));return (data||[]).map(r=>({...r,_supporters:supMap[r.id]||[],_comments:comMap[r.id]||[]}))}
function requestCard(r,admin=false){const supportCount=r._supporters?.length||0, supported=r._supporters?.includes(currentUser?.id),own=r.user_id===currentUser?.id;const replyCount=(r._comments||[]).length;return `<article class="request-card"><div class="request-head"><div><div class="request-author">${avatarHTML(r.profiles||{})}<div><h3>${escapeHTML(r.title)}</h3><p class="muted">@${escapeHTML(r.profiles?.username||"user")} · ${formatDate(r.created_at)} · ${escapeHTML(r.visibility)}</p></div></div></div><span class="tag status-${escapeHTML(r.status)}">${escapeHTML(r.status)}</span></div><p>${escapeHTML(r.description)}</p>${r.file_path?`<button class="text-btn" onclick="downloadRequestFile('${r.id}')">Download file referensi${r.file_name?`: ${escapeHTML(r.file_name)}`:""}</button>`:""}<div class="request-actions">${!own?`<button class="btn small ${supported?'':'ghost'}" onclick="toggleSupport('${r.id}')">☑ ${supported?'Kamu setuju':'Centang untuk setujui requestan ini'}</button>`:''}<b>${supportCount} User setuju dengan request ini</b>${own&&!admin?`<button class="btn small ghost" onclick="editRequest('${r.id}')">Edit</button>`:''}</div><div class="request-comments"><h4>${replyCount} komentar</h4>${commentThread(r._comments||[],"request",r.id)}</div>${currentUser?`<div class="comment-compose compact"><input class="input" id="requestComment_${r.id}" placeholder="Komentar request ini"><button class="btn small" onclick="postRequestComment('${r.id}')">Kirim</button></div>`:''}${admin?`<div class="request-admin-actions"><button class="btn small" onclick="setRequestStatus('${r.id}','accepted')">Setujui</button><button class="btn small ghost" onclick="setRequestStatus('${r.id}','rejected')">Tolak</button><button class="btn small danger" onclick="deleteRequest('${r.id}')">Hapus</button></div>`:''}</article>`}
async function loadRequestsPage(){const u=!!currentUser;$("requestGate").innerHTML=u?'':'<div class="panel"><h3>Login diperlukan</h3><p class="muted">Login untuk membuat, mendukung, dan membalas request.</p><button class="btn" id="requestLogin">Login / Register</button></div>';const btn=$("requestLogin");if(btn)btn.onclick=()=>openAuth();$("manageMyRequestsBtn").classList.toggle("hidden",!u);if(u){const data=await fetchRequests('mine');myRequestsCache=data;renderMyRequests(data)}else $("myRequestsPanel").classList.add("hidden");publicRequestsCache=await fetchRequests('public');renderPublicRequests(publicRequestsCache)}
function renderPublicRequests(arr){const q=$("requestSearch").value.toLowerCase();const list=arr.filter(r=>(r.title+" "+r.description+" "+(r.profiles?.username||"")).toLowerCase().includes(q));$("publicRequests").innerHTML=list.map(r=>requestCard(r)).join("")||"<p class='muted'>Belum ada request public.</p>"}
function renderMyRequests(arr){$("myRequestsList").innerHTML=arr.map(r=>requestCard(r,false)).join("")||"<p class='muted'>Kamu belum membuat request.</p>"}
$("manageMyRequestsBtn").onclick=()=>$("myRequestsPanel").classList.toggle("hidden");$("addRequestBtn").onclick=()=>openRequestEditor();$("cancelRequestEdit").onclick=()=>resetRequestForm();$("requestSearch").oninput=()=>renderPublicRequests(publicRequestsCache);
function openRequestEditor(r){if(!requireAuth())return;$("requestForm").classList.remove("hidden");$("requestFormTitle").textContent=r?"Edit Request":"Add Request";$("editRequestId").value=r?.id||"";$("reqTitle").value=r?.title||"";$("reqText").value=r?.description||"";$("reqVisibility").value=r?.visibility||"private";$("reqFile").value="";$("requestForm").scrollIntoView({behavior:"smooth",block:"start"})}
function resetRequestForm(){$("requestForm").classList.add("hidden");$("requestForm").reset();$("editRequestId").value="";$("requestFormTitle").textContent="Add Request"}
window.editRequest=async id=>{const r=myRequestsCache.find(x=>x.id===id);if(r)openRequestEditor(r)}
$("requestForm").onsubmit=async e=>{e.preventDefault();if(!requireAuth())return;const id=$("editRequestId").value,title=$("reqTitle").value.trim(),description=$("reqText").value.trim(),visibility=$("reqVisibility").value,file=$("reqFile").files[0];if(!title||!description)return;if(id){const {data:old}=await sb.from("requests").select("user_id,file_path").eq("id",id).single();if(!old||old.user_id!==currentUser.id)return toast("Request tidak ditemukan.",true);let filePath=old.file_path||null,fileName=null;if(file){if(file.type!="image/png"&&file.type!="application/pdf"&&file.type!="application/zip"&&file.size>8*1024*1024)return toast("File terlalu besar atau tipe tidak didukung.",true);const path=`${currentUser.id}/${id}/${crypto.randomUUID()}_${file.name}`;const up=await sb.storage.from("request-files").upload(path,file,{upsert:false});if(up.error)return toast(up.error.message,true);filePath=path;fileName=file.name}const {error}=await sb.from("requests").update({title,description,visibility,file_path:filePath,file_name:fileName||undefined,updated_at:new Date().toISOString()}).eq("id",id);if(error)return toast(error.message,true);toast("Request diperbarui")}else{const {data:created,error}=await sb.from("requests").insert({user_id:currentUser.id,title,description,visibility}).select().single();if(error)return toast(error.message,true);if(file){if(file.size>8*1024*1024)return toast("File maksimal 8 MB.",true);const path=`${currentUser.id}/${created.id}/${crypto.randomUUID()}_${file.name}`;const up=await sb.storage.from("request-files").upload(path,file,{upsert:false});if(up.error){await sb.from("requests").delete().eq("id",created.id);return toast(up.error.message,true)}await sb.from("requests").update({file_path:path,file_name:file.name}).eq("id",created.id)}toast("Request tersimpan")}resetRequestForm();await loadRequestsPage()}
window.toggleSupport=async id=>{if(!requireAuth())return;const r=[...publicRequestsCache,...myRequestsCache].find(x=>x.id===id);if(!r||r.user_id===currentUser.id)return;const exists=r._supporters?.includes(currentUser.id);const result=exists?await sb.from("request_supports").delete().eq("request_id",id).eq("user_id",currentUser.id):await sb.from("request_supports").insert({request_id:id,user_id:currentUser.id});if(result.error)return toast(result.error.message,true);await loadRequestsPage()}
window.postRequestComment=async id=>{if(!requireAuth())return;const el=$("requestComment_"+id);const body=el?.value.trim();if(!body)return;const {error}=await sb.from("request_comments").insert({request_id:id,user_id:currentUser.id,body});if(error)return toast(error.message,true);await loadRequestsPage()}
window.replyRequest=async(id,parentId)=>{if(!requireAuth())return;const el=$("requestreplytext_"+parentId),body=el?.value.trim();if(!body)return;const {error}=await sb.from("request_comments").insert({request_id:id,user_id:currentUser.id,parent_id:parentId,body});if(error)return toast(error.message,true);await loadRequestsPage()}
window.downloadRequestFile=async id=>{if(!requireAuth())return;const all=[...publicRequestsCache,...myRequestsCache];const r=all.find(x=>x.id===id);if(!r?.file_path)return;const {data,error}=await sb.storage.from("request-files").createSignedUrl(r.file_path,300);if(error)return toast(error.message,true);window.open(data.signedUrl,"_blank")}

async function loadAdminRequests(){if(!requireAdmin())return;const {data,error}=await sb.from("requests").select("*,profiles(username,display_name,avatar_url)").order("created_at",{ascending:false});if(error)return toast(error.message,true);const ids=(data||[]).map(x=>x.id);const [{data:supports},{data:comments}]=ids.length?await Promise.all([sb.from("request_supports").select("request_id,user_id").in("request_id",ids),sb.from("request_comments").select("id,request_id,user_id,parent_id,body,created_at,profiles(username,display_name,avatar_url)").in("request_id",ids).order("created_at",{ascending:true})]):[{data:[]},{data:[]}];const sm={};(supports||[]).forEach(x=>(sm[x.request_id]??=[]).push(x.user_id));const cm={};(comments||[]).forEach(x=>(cm[x.request_id]??=[]).push(x));let arr=(data||[]).map(r=>({...r,_supporters:sm[r.id]||[],_comments:cm[r.id]||[]}));const q=$("adminRequestSearch").value.toLowerCase(),st=$("adminRequestStatus").value;arr=arr.filter(r=>(!q||(r.title+" "+r.description+" "+(r.profiles?.username||"")).toLowerCase().includes(q))&&(!st||r.status===st));$("adminRequestList").innerHTML=arr.map(r=>requestCard(r,true)).join("")||"<p class='muted'>Tidak ada request.</p>"}
$("adminRequestSearch").oninput=loadAdminRequests;$("adminRequestStatus").onchange=loadAdminRequests;
window.setRequestStatus=async(id,status)=>{if(!requireAdmin())return;const {error}=await sb.from("requests").update({status,updated_at:new Date().toISOString()}).eq("id",id);if(error)return toast(error.message,true);await loadAdminRequests();await loadRequestsPage();toast("Status request diperbarui")};window.deleteRequest=async id=>{if(!requireAdmin()||!confirm("Hapus request ini?"))return;const {error}=await sb.from("requests").delete().eq("id",id);if(error)return toast(error.message,true);await loadAdminRequests();toast("Request dihapus")}

async function renderProfile(){if(!currentProfile)return;$("profileUsername").value=currentProfile.username;$("profileUsernameLabel").textContent=`@${currentProfile.username}`;$("profileHeading").textContent=currentProfile.display_name||currentProfile.username;$("profileName").value=currentProfile.display_name||"";$("profileAvatarPreview").outerHTML=avatarHTML(currentProfile,"big").replace('<div class="avatar big">','<div id="profileAvatarPreview" class="avatar big">')}
$("profileForm").onsubmit=async e=>{e.preventDefault();if(!requireAuth())return;const display_name=$("profileName").value.trim()||currentProfile.username;let avatar_url=currentProfile.avatar_url||null;const file=$("profileAvatarFile").files[0];if(file){if(file.type!=="image/png")return toast("Foto profil harus PNG.",true);if(file.size>2*1024*1024)return toast("PNG maksimal 2 MB.",true);const path=`${currentUser.id}/profile.png`;const up=await sb.storage.from("avatars").upload(path,file,{upsert:true,contentType:"image/png"});if(up.error)return toast(up.error.message,true);avatar_url=sb.storage.from("avatars").getPublicUrl(path).data.publicUrl+`?v=${Date.now()}`}const {data,error}=await sb.from("profiles").update({display_name,avatar_url,updated_at:new Date().toISOString()}).eq("id",currentUser.id).select().single();if(error)return toast(error.message,true);currentProfile=data;await renderProfile();updateNav();toast("Profile disimpan")}
$("removeAvatarBtn").onclick=async()=>{if(!requireAuth())return;await sb.storage.from("avatars").remove([`${currentUser.id}/profile.png`]);const {data,error}=await sb.from("profiles").update({avatar_url:null,updated_at:new Date().toISOString()}).eq("id",currentUser.id).select().single();if(error)return toast(error.message,true);currentProfile=data;renderProfile();toast("Foto profil dihapus")}
$("passwordForm").onsubmit=async e=>{e.preventDefault();if(!requireAuth())return;const oldP=$("oldPassword").value,newP=$("newPassword").value;const check=await sb.auth.signInWithPassword({email:usernameEmail(currentProfile.username),password:oldP});if(check.error)return toast("Password lama salah.",true);const {error}=await sb.auth.updateUser({password:newP});if(error)return toast(error.message,true);e.target.reset();toast("Password berhasil diubah")}

renderCategoryChoices([]);updateNav();
